// Copyright 2026 Siddharth Viswanathan
// This file was fully generated by Codex and may contain modifications by Siddharth Viswanathan as of 2026.
// SPDX-License-Identifier: Apache-2.0

package gossip

import (
	"os"
	"path/filepath"
	"testing"
)

func TestMain(m *testing.M) {
	identityDir, err := os.MkdirTemp("", "vcs-gossip-tests-identity-*")
	if err != nil {
		panic(err)
	}
	_ = os.Setenv(identityDirEnvVar, filepath.Join(identityDir, "vcs", "gossip"))

	code := m.Run()
	_ = os.RemoveAll(identityDir)
	os.Exit(code)
}
